export * from "./resolve.js";
export * from "./normalize.js";
export * from "./domain-check.js";
export * from "./capability-check.js";
export * from "./frontend-semantic-lowering.js";
export * from "./component-lowering.js";
export * from "./atomic-validation.js";
export * from "./platform-lowering.js";
export * from "./target-planning.js";
